### PR TITLE
Fixed nearly all tests

### PR DESCRIPTION
**Pull request by lhns**
I fixed all the tests except the tricky-paths one.

### CODE REVIEW

**Comment by svrooij** [comment]
Thanks for your first contribution! I’m not sure how to continue from here.

Are you absolutely sure the changes to the library itself don’t break anything? Then we can continue on releasing a new version

**Comment by svrooij** [comment]
Sorry by the way that I didn’t respond earlier, didn’t got a notification.

**Comment by lhns** [comment]
No problem! Yeah your code style updates were pretty substential but I think the library is a lot more modern as a result of that. I don't really know how to fix the tricky-paths test but all the other tests seem fine. I also tested this lib in conjunction with https://github.com/biddster/node-red-contrib-ftp-server and allthough I therefore only used a subset of the library it seems to be in a pretty good and functional state.
One thing that would probably be nice for the future would be to remove the tricky-paths directories from the git repo and create them just before the test runs because the strange path names cause a lot of issues on windows and on some git clients.

**Comment by svrooij** [comment]
> Yeah your code style updates were pretty substential but I think the library is a lot more modern as a result of that.

That wasn't a manual job 😉 That was me executing `eslint --fix` I felt trusted enough in the eslint team to get a good hang of it.

I just merged as a regular pr, you should get your name attached to it if you contribute something.

**Pull request merged**
